# ncmpcpp
# Autogenerated from man page /usr/share/man/man1/ncmpcpp.1.gz
complete -c ncmpcpp -s h -l host -d 'Connect to server at host [localhost]'
complete -c ncmpcpp -s p -l port -d 'Connect to server at port [6600]'
complete -c ncmpcpp -l current-song -d 'Print current song using given format and exit'
complete -c ncmpcpp -s c -l config -d 'Specify configuration file(s)'
complete -c ncmpcpp -l ignore-config-errors -d 'Ignore unknown and invalid options in configuration files'
complete -c ncmpcpp -s b -l bindings -d 'Specify bindings file(s)'
complete -c ncmpcpp -s s -l screen -d 'Specify the startup screen (<name> may be: help, playlist, browser, search_en…'
complete -c ncmpcpp -s S -l slave-screen -d 'Specify the startup slave screen (<name> may be: help, playlist, browser, sea…'
complete -c ncmpcpp -s q -l quiet -d 'Suppress logs and excess output'
complete -c ncmpcpp -s '?' -l help -d 'Display help'

