# physlock
# Autogenerated from man page /usr/share/man/man1/physlock.1.gz
complete -c physlock -s d -d 'Fork and detach physlock before prompting for authentication'
complete -c physlock -s h -d 'Print brief usage information to standard output and exit'
complete -c physlock -s l -d 'Only lock console switching and exit'
complete -c physlock -s L -d 'Only enable (unlock) console switching and exit'
complete -c physlock -s m -d 'Mute kernel messages on console while physlock is running'
complete -c physlock -s p -d 'Display  MSG before the password prompt'
complete -c physlock -s s -d 'Disable SysRq mechanism while physlock is running'
complete -c physlock -s v -d 'Print version information to standard output and exit.  AUTHORS'

